name: ZEIT dev

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: ZEIT Now Deployment
      uses: amondnet/now-deployment@v1
      with:
        zeit-token: ${{ secrets.ZEIT_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
      env:
          NOW_ORG_ID: yF539Eg0ZhDQiKXD0aBCIjCO
          NOW_PROJECT_ID: QmPzLRW3xQVzcQwnxAAyQUKYn1fU1XYb8kuowp9Y5Ygm2q
